development:
  adapter: postgresql
  encoding: unicode
  database: login_development
  pool: 5
  username: eduardobaik
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: login_test
  pool: 5
  username: eduardobaik
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: login_production
  pool: 5
  username: eduardobaik
  password: